[pytest]
# Базовый модуль настроек Django для запуска тестов через pytest.
DJANGO_SETTINGS_MODULE = loyalty_viewer.settings

# Подхватываем привычные имена тестовых файлов в проекте.
python_files = tests.py test_*.py *_tests.py
testpaths = guests/tests

# Краткая сводка по упавшим/пропущенным тестам.
addopts = -ra
