# Generated by Django 5.2.7 on 2025-11-18 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guest',
            options={'managed': True},
        ),
    ]
