# Generated by Django 5.2.7 on 2025-12-17 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0002_alter_guest_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guest',
            options={'managed': False},
        ),
    ]
