# Generated by Django 5.2.7 on 2025-12-17 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0003_alter_guest_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestCategoryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'guest_category_assignments',
                'managed': True,
            },
        ),
    ]
