# Generated by Django 5.2.7 on 2026-02-06 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0004_guestcategoryassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('message_text', models.TextField()),
                ('created_by', models.CharField(default='test_user', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'message_templates',
            },
        ),
    ]
