# Generated by Codex on 2026-03-16

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Базовая миграция для ядра универсальной очереди.

    Создаёт:
    1. Справочник ботов (Telegram/Max/VK).
    2. Привязки гостя к ботам с признаком основного канала.
    3. Универсальные задачи на отправку сообщений.
    """

    dependencies = [
        ("guests", "0005_messagetemplate"),
    ]

    operations = [
        migrations.CreateModel(
            name="BotProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.SlugField(help_text="Уникальный код профиля бота для внутренних интеграций.", max_length=64, unique=True)),
                ("name", models.CharField(max_length=150)),
                (
                    "provider_type",
                    models.CharField(
                        choices=[("telegram", "Telegram"), ("max", "MAX"), ("vk", "VK")],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "token",
                    models.TextField(
                        blank=True,
                        help_text="Токен/секрет доступа. На данном этапе хранится в открытом виде.",
                        null=True,
                    ),
                ),
                (
                    "settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Параметры провайдера в JSON (таймауты, базовые URL, флаги и пр.).",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Профиль бота",
                "verbose_name_plural": "Профили ботов",
                "db_table": "bot_profiles",
            },
        ),
        migrations.CreateModel(
            name="GuestBotBinding",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "external_chat_id",
                    models.CharField(
                        help_text="Идентификатор чата/peer, куда отправляются сообщения.",
                        max_length=128,
                    ),
                ),
                (
                    "external_user_id",
                    models.CharField(
                        blank=True,
                        help_text="Опциональный идентификатор пользователя у провайдера.",
                        max_length=128,
                        null=True,
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Признак основного бота для гостя.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_opt_in", models.BooleanField(default=True)),
                ("is_stop_sending", models.BooleanField(default=False)),
                ("last_error", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guest_bindings",
                        to="guests.botprofile",
                    ),
                ),
                (
                    "guest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bot_bindings",
                        to="guests.guest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привязка гостя к боту",
                "verbose_name_plural": "Привязки гостей к ботам",
                "db_table": "guest_bot_bindings",
            },
        ),
        migrations.CreateModel(
            name="DispatchTask",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("mailing", "Массовая рассылка"),
                            ("webhook", "Веб-хук"),
                            ("manual", "Ручной запуск"),
                            ("system", "Системная задача"),
                        ],
                        default="mailing",
                        max_length=32,
                    ),
                ),
                (
                    "provider_type",
                    models.CharField(
                        choices=[("telegram", "Telegram"), ("max", "MAX"), ("vk", "VK")],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[("high", "Высокий"), ("normal", "Обычный"), ("bulk", "Пакетный")],
                        db_index=True,
                        default="bulk",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает отправки"),
                            ("in_progress", "В обработке"),
                            ("done", "Успешно отправлено"),
                            ("failed", "Ошибка отправки"),
                            ("canceled", "Отменено"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("external_chat_id", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Полезная нагрузка задачи (шаблон, переменные, метаданные).",
                    ),
                ),
                ("message_text", models.TextField(blank=True, default="")),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True,
                        help_text="Ключ дедупликации задачи для безопасных повторов.",
                        max_length=150,
                        null=True,
                        unique=True,
                    ),
                ),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "available_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="Время, начиная с которого задачу можно брать в обработку.",
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("attempt", models.PositiveIntegerField(default=0)),
                ("max_attempts", models.PositiveIntegerField(default=5)),
                ("last_error", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bot_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dispatch_tasks",
                        to="guests.botprofile",
                    ),
                ),
                (
                    "guest",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dispatch_tasks",
                        to="guests.guest",
                    ),
                ),
                (
                    "guest_binding",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dispatch_tasks",
                        to="guests.guestbotbinding",
                    ),
                ),
            ],
            options={
                "verbose_name": "Задача диспетчера",
                "verbose_name_plural": "Задачи диспетчера",
                "db_table": "dispatch_tasks",
            },
        ),
        migrations.AddConstraint(
            model_name="guestbotbinding",
            constraint=models.UniqueConstraint(fields=("guest", "bot"), name="guest_bot_bindings_guest_bot_uniq"),
        ),
        migrations.AddConstraint(
            model_name="guestbotbinding",
            constraint=models.UniqueConstraint(
                condition=models.Q(is_primary=True),
                fields=("guest",),
                name="guest_bot_bindings_primary_uniq",
            ),
        ),
        migrations.AddIndex(
            model_name="guestbotbinding",
            index=models.Index(fields=["bot", "is_active"], name="gbb_bot_active_idx"),
        ),
        migrations.AddIndex(
            model_name="guestbotbinding",
            index=models.Index(fields=["guest", "is_active"], name="gbb_guest_active_idx"),
        ),
        migrations.AddConstraint(
            model_name="dispatchtask",
            constraint=models.CheckConstraint(
                condition=models.Q(attempt__lte=models.F("max_attempts")),
                name="dispatch_tasks_attempt_lte_max",
            ),
        ),
        migrations.AddIndex(
            model_name="dispatchtask",
            index=models.Index(
                fields=["provider_type", "priority", "status", "available_at"],
                name="dispatch_tasks_lane_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dispatchtask",
            index=models.Index(fields=["status", "available_at"], name="dispatch_tasks_status_available_idx"),
        ),
        migrations.AddIndex(
            model_name="dispatchtask",
            index=models.Index(fields=["guest", "created_at"], name="dispatch_tasks_guest_idx"),
        ),
    ]

