# Generated by Codex on 2026-03-16

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Расширение модели DispatchTask для безопасной диспетчеризации.

    Добавляет:
    1. Статус queued (задача уже поставлена в Redis-очередь).
    2. Метку enqueued_at для контроля повторной постановки.
    3. queue_name для прозрачного аудита маршрутизации по lane-очередям.
    """

    dependencies = [
        ("guests", "0006_universal_queue_core"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dispatchtask",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидает отправки"),
                    ("queued", "Поставлено в Redis-очередь"),
                    ("in_progress", "В обработке"),
                    ("done", "Успешно отправлено"),
                    ("failed", "Ошибка отправки"),
                    ("canceled", "Отменено"),
                ],
                db_index=True,
                default="pending",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="dispatchtask",
            name="enqueued_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Время постановки задачи в Redis-очередь провайдера.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="dispatchtask",
            name="queue_name",
            field=models.CharField(
                blank=True,
                help_text="Физическое имя Redis-очереди (lane), куда отправлена задача.",
                max_length=120,
                null=True,
            ),
        ),
    ]
