# Generated by Codex on 2026-03-16

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Добавляет безопасный способ хранения ссылки на секрет токена бота.

    Поле `secret_ref` хранит имя переменной окружения, из которой
    приложение должно читать токен во время выполнения.
    """

    dependencies = [
        ("guests", "0007_dispatchtask_queue_tracking"),
    ]

    operations = [
        migrations.AddField(
            model_name="botprofile",
            name="secret_ref",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text=(
                    "Ссылка на секрет в окружении (например, BOT_TOKEN_TG_MAIN). "
                    "Если указано, токен берётся из переменной окружения, а не из БД."
                ),
                max_length=150,
                null=True,
            ),
        ),
    ]
