# Generated by Django 5.2.7 on 2026-03-16 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0008_botprofile_secret_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestChannelLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_chat_id', models.CharField(blank=True, max_length=64, null=True)),
                ('is_opt_in', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_stop_sending', models.BooleanField(default=False)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'guest_channel_links',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('scheduled_date', models.DateField()),
                ('scheduled_time_begin', models.DateTimeField()),
                ('scheduled_time_end', models.DateTimeField()),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('send_window_begin', models.TimeField()),
                ('send_window_end', models.TimeField()),
            ],
            options={
                'db_table': 'mailings',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MailingChannel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('channel_kind', models.CharField(choices=[('phone_telegram', 'Телефон Телеграмм'), ('phone_telegram_bot', 'Телефон Телеграмм Бот'), ('email', 'Электронная почта')], max_length=50)),
                ('token', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'mailing_channels',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MailingChannelLink',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'mailing_channel_links',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MailingGuest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('text_mailing_list', models.TextField()),
                ('scheduled_datetime', models.DateTimeField()),
                ('status', models.CharField(choices=[('planned', 'запланировано'), ('in_progress', 'выполняется'), ('done', 'завершено'), ('error', 'ошибка')], default='planned', max_length=20)),
                ('error_description', models.TextField(blank=True, null=True)),
                ('external_id', models.CharField(blank=True, max_length=32, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_status', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'mailing_guests',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='messagetemplate',
            options={'managed': False},
        ),
        migrations.RenameIndex(
            model_name='dispatchtask',
            new_name='dispatch_tasks_status_avl_idx',
            old_name='dispatch_tasks_status_available_idx',
        ),
    ]
