# Generated by Django 5.2.7 on 2026-03-17 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0009_guestchannellink_mailing_mailingchannel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='guest',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='guestcategory',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='guestcategoryassignment',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='guestchannellink',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='mailing',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='mailingchannel',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='mailingchannellink',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='mailingguest',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='messagetemplate',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='restaurant',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='visithistory',
            options={'managed': True},
        ),
    ]
