# Generated by Django 5.2.7 on 2026-03-17 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0011_remove_guest_is_stop_sending_category_external_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='queue_priority',
            field=models.CharField(choices=[('high', 'Высокий'), ('normal', 'Обычный'), ('bulk', 'Массовый')], default='bulk', help_text='Приоритет задач рассылки в универсальной очереди.', max_length=20),
        ),
        migrations.AddField(
            model_name='mailing',
            name='target_mode',
            field=models.CharField(choices=[('primary_only', 'Только основной бот'), ('all_bots', 'Все активные боты')], default='primary_only', help_text='Режим выбора целей: только основной бот или все активные боты гостя.', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='mailing',
            constraint=models.CheckConstraint(condition=models.Q(('target_mode__in', ['primary_only', 'all_bots'])), name='mailings_target_mode_chk'),
        ),
        migrations.AddConstraint(
            model_name='mailing',
            constraint=models.CheckConstraint(condition=models.Q(('queue_priority__in', ['high', 'normal', 'bulk'])), name='mailings_queue_priority_chk'),
        ),
    ]
