"""
Миграция параметров универсальной очереди для рассылок.

Важно:
1. В ряде окружений legacy-таблицы `mailings` и `mailing_guests` физически отсутствуют,
   хотя состояние миграций уже ссылается на эти модели.
2. Перед добавлением новых полей `queue_priority` и `target_mode` безопасно
   создаём базовые таблицы, если их нет.
"""

# Generated by Django 5.2.7 on 2026-03-17 13:08

from django.db import migrations, models


BOOTSTRAP_MAILING_TABLES_SQL = """
CREATE TABLE IF NOT EXISTS mailings (
    id bigserial PRIMARY KEY,
    name varchar(150) NOT NULL,
    scheduled_date date NOT NULL,
    scheduled_time_begin timestamp with time zone NOT NULL,
    scheduled_time_end timestamp with time zone NOT NULL,
    is_active boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    send_window_begin time NOT NULL,
    send_window_end time NOT NULL,
    template_id bigint NOT NULL
);

CREATE TABLE IF NOT EXISTS mailing_guests (
    id bigserial PRIMARY KEY,
    phone varchar(50),
    email varchar(150),
    text_mailing_list text NOT NULL,
    scheduled_datetime timestamp with time zone NOT NULL,
    status varchar(20) NOT NULL DEFAULT 'planned',
    error_description text,
    external_id varchar(32),
    sent_at timestamp with time zone,
    delivery_status varchar(50),
    created_at timestamp with time zone NOT NULL,
    guest_id bigint NOT NULL,
    mailing_id bigint NOT NULL
);

-- Если таблицы уже существовали в legacy-схеме (без нужных колонок),
-- безопасно добавляем недостающие поля.
ALTER TABLE mailings
    ADD COLUMN IF NOT EXISTS template_id bigint;
ALTER TABLE mailing_guests
    ADD COLUMN IF NOT EXISTS guest_id bigint;
ALTER TABLE mailing_guests
    ADD COLUMN IF NOT EXISTS mailing_id bigint;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'mailings_time_chk'
    ) THEN
        ALTER TABLE mailings
        ADD CONSTRAINT mailings_time_chk
        CHECK (scheduled_time_begin <= scheduled_time_end);
    END IF;
END
$$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'mailing_guests_uniq'
    ) THEN
        ALTER TABLE mailing_guests
        ADD CONSTRAINT mailing_guests_uniq
        UNIQUE (mailing_id, guest_id);
    END IF;
END
$$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'mailing_guests_status_chk'
    ) THEN
        ALTER TABLE mailing_guests
        ADD CONSTRAINT mailing_guests_status_chk
        CHECK (status IN ('planned', 'in_progress', 'done', 'error'));
    END IF;
END
$$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'mailings_template_id_fk'
    ) THEN
        ALTER TABLE mailings
        ADD CONSTRAINT mailings_template_id_fk
        FOREIGN KEY (template_id)
        REFERENCES message_templates(id)
        ON DELETE RESTRICT;
    END IF;
END
$$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'mailing_guests_guest_id_fk'
    ) THEN
        ALTER TABLE mailing_guests
        ADD CONSTRAINT mailing_guests_guest_id_fk
        FOREIGN KEY (guest_id)
        REFERENCES guests(id)
        ON DELETE CASCADE;
    END IF;
END
$$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'mailing_guests_mailing_id_fk'
    ) THEN
        ALTER TABLE mailing_guests
        ADD CONSTRAINT mailing_guests_mailing_id_fk
        FOREIGN KEY (mailing_id)
        REFERENCES mailings(id)
        ON DELETE CASCADE;
    END IF;
END
$$;

CREATE INDEX IF NOT EXISTS mailing_guests_mailing_id_idx
    ON mailing_guests (mailing_id);
CREATE INDEX IF NOT EXISTS mailing_guests_status_idx
    ON mailing_guests (status);
CREATE INDEX IF NOT EXISTS mailing_guests_scheduled_idx
    ON mailing_guests (scheduled_datetime);
"""


class Migration(migrations.Migration):
    dependencies = [
        ("guests", "0011_remove_guest_is_stop_sending_category_external_id_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            sql=BOOTSTRAP_MAILING_TABLES_SQL,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddField(
            model_name="mailing",
            name="queue_priority",
            field=models.CharField(
                choices=[("high", "Высокий"), ("normal", "Обычный"), ("bulk", "Массовый")],
                default="bulk",
                help_text="Приоритет задач рассылки в универсальной очереди.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="mailing",
            name="target_mode",
            field=models.CharField(
                choices=[("primary_only", "Только основной бот"), ("all_bots", "Все активные боты")],
                default="primary_only",
                help_text="Режим выбора целей: только основной бот или все активные боты гостя.",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="mailing",
            constraint=models.CheckConstraint(
                condition=models.Q(("target_mode__in", ["primary_only", "all_bots"])),
                name="mailings_target_mode_chk",
            ),
        ),
        migrations.AddConstraint(
            model_name="mailing",
            constraint=models.CheckConstraint(
                condition=models.Q(("queue_priority__in", ["high", "normal", "bulk"])),
                name="mailings_queue_priority_chk",
            ),
        ),
    ]

