# Generated by Django 5.2.7 on 2026-03-17 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0012_mailing_queue_priority_mailing_target_mode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingBotProfileLink',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('bot_profile', models.ForeignKey(db_column='bot_profile_id', on_delete=django.db.models.deletion.RESTRICT, related_name='mailing_links', to='guests.botprofile')),
                ('mailing', models.ForeignKey(db_column='mailing_id', on_delete=django.db.models.deletion.CASCADE, related_name='bot_profile_links', to='guests.mailing')),
            ],
            options={
                'db_table': 'mailing_bot_profile_links',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='mailing',
            name='bot_profiles',
            field=models.ManyToManyField(help_text='Список конкретных ботов, через которые должна идти рассылка.', related_name='mailings', through='guests.MailingBotProfileLink', to='guests.botprofile'),
        ),
        migrations.AddIndex(
            model_name='mailingbotprofilelink',
            index=models.Index(fields=['mailing'], name='mbpl_mailing_id_idx'),
        ),
        migrations.AddIndex(
            model_name='mailingbotprofilelink',
            index=models.Index(fields=['bot_profile'], name='mbpl_bot_profile_id_idx'),
        ),
        migrations.AddConstraint(
            model_name='mailingbotprofilelink',
            constraint=models.UniqueConstraint(fields=('mailing', 'bot_profile'), name='mailing_bot_profile_links_uniq'),
        ),
    ]
