"""
Миграция удаления legacy-сущностей старой модели рассылки.

Что удаляется из состояния Django:
1. `Mailing.channels` (legacy many-to-many по каналам);
2. `MailingChannel`, `MailingChannelLink`, `GuestChannelLink`.

Почему миграция безопасная:
- в части БД используется `DROP TABLE IF EXISTS`, поэтому миграция проходит
  как на старых базах (где таблицы были), так и на новых (где их никогда не было).
"""

# Generated by Django 5.2.7 on 2026-03-17 14:21

from django.db import migrations


LEGACY_DROP_SQL = """
DROP TABLE IF EXISTS mailing_channel_links CASCADE;
DROP TABLE IF EXISTS mailing_channels CASCADE;
DROP TABLE IF EXISTS guest_channel_links CASCADE;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("guests", "0013_mailingbotprofilelink_mailing_bot_profiles_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=LEGACY_DROP_SQL,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name="mailingchannellink",
                    name="channel",
                ),
                migrations.RemoveField(
                    model_name="mailing",
                    name="channels",
                ),
                migrations.RemoveField(
                    model_name="mailingchannellink",
                    name="mailing",
                ),
                migrations.DeleteModel(
                    name="GuestChannelLink",
                ),
                migrations.DeleteModel(
                    name="MailingChannel",
                ),
                migrations.DeleteModel(
                    name="MailingChannelLink",
                ),
            ],
        ),
    ]
