"""
Миграция удаления legacy-сущностей старой модели рассылки.

Что удаляется:
1. `Mailing.channels` (legacy many-to-many по каналам);
2. `MailingChannel`, `MailingChannelLink`, `GuestChannelLink`.

Причина:
Проект полностью переведён на универсальную очередь и модель привязок
`GuestBotBinding` + `BotProfile`, поэтому старые таблицы больше не используются.
"""

# Generated by Django 5.2.7 on 2026-03-17 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0013_mailingbotprofilelink_mailing_bot_profiles_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailingchannellink',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='channels',
        ),
        migrations.RemoveField(
            model_name='mailingchannellink',
            name='mailing',
        ),
        migrations.DeleteModel(
            name='GuestChannelLink',
        ),
        migrations.DeleteModel(
            name='MailingChannel',
        ),
        migrations.DeleteModel(
            name='MailingChannelLink',
        ),
    ]
