"""
Миграция добавляет явную связь `DispatchTask -> MailingGuest`.

Назначение:
1. Упростить диагностику массовых рассылок в технической админке;
2. Позволить быстро переходить от задачи доставки к исходной строке кампании.
"""

# Generated by Django 5.2.7 on 2026-03-17 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0014_remove_mailingchannellink_channel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchtask',
            name='mailing_guest',
            field=models.ForeignKey(blank=True, help_text='Ссылка на строку массовой рассылки (если задача создана из MailingGuest).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_tasks', to='guests.mailingguest'),
        ),
    ]
