"""
Миграция F13 (шаги 1-3): каркас автоматизированных уведомлений.

Что добавляет:
1. Новые сущности `NotificationScenario`, `NotificationEvent`,
   `NotificationScenarioBotProfileLink`;
2. Связи `DispatchTask -> notification_scenario/notification_event`
   для прозрачной трассировки источника задач доставки.
"""

# Generated by Django 5.2.7 on 2026-03-17 17:49

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0015_dispatchtask_mailing_guest'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('source_type', models.CharField(choices=[('webhook', 'Веб-хук'), ('schedule', 'Планировщик'), ('manual', 'Ручной запуск')], db_index=True, max_length=20)),
                ('source_ref', models.CharField(blank=True, db_index=True, help_text='Внешний идентификатор события (например webhook id).', max_length=150, null=True)),
                ('dedupe_key', models.CharField(help_text='Ключ дедупликации: повтор с тем же ключом не создаёт новую отправку.', max_length=180)),
                ('status', models.CharField(choices=[('new', 'Новое'), ('duplicated', 'Дубликат'), ('task_created', 'Задача создана'), ('skipped', 'Пропущено по правилам'), ('error', 'Ошибка обработки')], db_index=True, default='new', max_length=20)),
                ('event_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('planned_send_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Рассчитанное время, когда уведомление можно отправлять в очередь доставки.')),
                ('duplicate_hits', models.PositiveIntegerField(default=0)),
                ('last_duplicate_at', models.DateTimeField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Контекст события для рендера шаблона и аудита.')),
                ('coupon_code', models.CharField(blank=True, max_length=120, null=True)),
                ('coupon_external_id', models.CharField(blank=True, max_length=150, null=True)),
                ('coupon_expires_at', models.DateTimeField(blank=True, null=True)),
                ('error_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_events', to='guests.guest')),
            ],
            options={
                'verbose_name': 'Событие уведомления',
                'verbose_name_plural': 'События уведомлений',
                'db_table': 'notification_events',
            },
        ),
        migrations.AddField(
            model_name='dispatchtask',
            name='notification_event',
            field=models.ForeignKey(blank=True, help_text='Ссылка на событие, из которого сформирована задача доставки.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_tasks', to='guests.notificationevent'),
        ),
        migrations.CreateModel(
            name='NotificationScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Уникальный технический код сценария, например balance_changed.', max_length=80, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False, help_text='Служебный сценарий: запрещено удаление/изменение через пользовательский UI.')),
                ('trigger_type', models.CharField(choices=[('webhook', 'Веб-хук'), ('schedule', 'Планировщик'), ('manual', 'Ручной запуск')], db_index=True, default='webhook', max_length=20)),
                ('webhook_category_external_id', models.CharField(blank=True, db_index=True, help_text='Внешний category_id для webhook-сценариев (если используется).', max_length=64, null=True)),
                ('priority', models.CharField(choices=[('high', 'Высокий'), ('normal', 'Обычный'), ('bulk', 'Массовый')], default='normal', max_length=16)),
                ('target_mode', models.CharField(choices=[('primary_only', 'Только основной бот'), ('all_bots', 'Все активные боты')], default='primary_only', max_length=20)),
                ('distribution_mode', models.CharField(choices=[('immediate', 'Сразу'), ('uniform', 'Равномерно в окне')], default='immediate', max_length=20)),
                ('send_window_begin', models.TimeField(blank=True, null=True)),
                ('send_window_end', models.TimeField(blank=True, null=True)),
                ('timezone', models.CharField(default='Asia/Yekaterinburg', max_length=64)),
                ('cooldown_minutes', models.PositiveIntegerField(default=0, help_text='Минимальная пауза между отправками одному гостю по этому сценарию.')),
                ('max_per_day_per_guest', models.PositiveIntegerField(blank=True, help_text='Дневной лимит отправок одному гостю по сценарию (если задан).', null=True)),
                ('settings', models.JSONField(blank=True, default=dict, help_text='Расширенные параметры сценария в JSON.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='notification_scenarios', to='guests.messagetemplate')),
            ],
            options={
                'verbose_name': 'Сценарий уведомления',
                'verbose_name_plural': 'Сценарии уведомлений',
                'db_table': 'notification_scenarios',
            },
        ),
        migrations.AddField(
            model_name='notificationevent',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='guests.notificationscenario'),
        ),
        migrations.AddField(
            model_name='dispatchtask',
            name='notification_scenario',
            field=models.ForeignKey(blank=True, help_text='Ссылка на сценарий авто-уведомления (для задач не из MailingGuest).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_tasks', to='guests.notificationscenario'),
        ),
        migrations.CreateModel(
            name='NotificationScenarioBotProfileLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bot_profile', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='notification_scenario_links', to='guests.botprofile')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_profile_links', to='guests.notificationscenario')),
            ],
            options={
                'verbose_name': 'Связь сценария с ботом',
                'verbose_name_plural': 'Связи сценариев с ботами',
                'db_table': 'notification_scenario_bot_profile_links',
            },
        ),
        migrations.AddField(
            model_name='notificationscenario',
            name='bot_profiles',
            field=models.ManyToManyField(help_text='Список разрешённых ботов для этого сценария.', related_name='notification_scenarios', through='guests.NotificationScenarioBotProfileLink', to='guests.botprofile'),
        ),
        migrations.AddIndex(
            model_name='notificationevent',
            index=models.Index(fields=['status', 'planned_send_at'], name='ne_status_plan_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationevent',
            index=models.Index(fields=['guest', 'scenario', 'event_at'], name='ne_guest_scn_evt_idx'),
        ),
        migrations.AddConstraint(
            model_name='notificationevent',
            constraint=models.UniqueConstraint(fields=('scenario', 'dedupe_key'), name='ne_scenario_dedupe_uniq'),
        ),
        migrations.AddIndex(
            model_name='notificationscenariobotprofilelink',
            index=models.Index(fields=['scenario'], name='nsbpl_scenario_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationscenariobotprofilelink',
            index=models.Index(fields=['bot_profile'], name='nsbpl_bot_idx'),
        ),
        migrations.AddConstraint(
            model_name='notificationscenariobotprofilelink',
            constraint=models.UniqueConstraint(fields=('scenario', 'bot_profile'), name='nsbpl_scenario_bot_uniq'),
        ),
        migrations.AddIndex(
            model_name='notificationscenario',
            index=models.Index(fields=['is_active', 'trigger_type'], name='ns_active_trigger_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationscenario',
            index=models.Index(fields=['code'], name='ns_code_idx'),
        ),
        migrations.AddConstraint(
            model_name='notificationscenario',
            constraint=models.CheckConstraint(condition=models.Q(('priority__in', ['high', 'normal', 'bulk'])), name='ns_priority_chk'),
        ),
        migrations.AddConstraint(
            model_name='notificationscenario',
            constraint=models.CheckConstraint(condition=models.Q(('target_mode__in', ['primary_only', 'all_bots'])), name='ns_target_mode_chk'),
        ),
        migrations.AddConstraint(
            model_name='notificationscenario',
            constraint=models.CheckConstraint(condition=models.Q(('distribution_mode__in', ['immediate', 'uniform'])), name='ns_distribution_mode_chk'),
        ),
    ]
