# Generated by Django 5.2.7 on 2026-03-19 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0018_seed_inactive_notification_scenarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='OlapCheckSyncJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(db_index=True, help_text='Детерминированный ключ задачи для защиты от дублей.', max_length=150, unique=True)),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('loaded', 'Загружена'), ('retry', 'Повторить позже'), ('failed', 'Ошибка'), ('skipped', 'Пропущена')], db_index=True, default='new', max_length=20)),
                ('source_webhook_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('organization_id', models.CharField(blank=True, max_length=64, null=True)),
                ('terminal_group_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('order_number', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('order_external_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('transaction_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('event_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('business_date', models.DateField(blank=True, db_index=True, null=True)),
                ('department_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('department_code', models.CharField(blank=True, max_length=32, null=True)),
                ('restoraunt_group_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('next_try_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('loaded_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest', models.ForeignKey(blank=True, help_text='Гость, для которого требуется дозагрузка чека (если определён).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='olap_check_sync_rows', to='guests.guest')),
            ],
            options={
                'verbose_name': 'Журнал синхронизации чеков с OLAP',
                'verbose_name_plural': 'Журнал синхронизации чеков с OLAP',
                'db_table': 'olap_check_sync_journal',
            },
        ),
        migrations.CreateModel(
            name='OlapSalesRawLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_fingerprint', models.CharField(db_index=True, help_text='SHA-256 ключ строки позиции для защиты от дублей.', max_length=64, unique=True)),
                ('business_date', models.DateField(db_index=True)),
                ('department_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('department_code', models.CharField(blank=True, max_length=32, null=True)),
                ('department_name', models.CharField(blank=True, max_length=255, null=True)),
                ('restaurant_section_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('restoraunt_group_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('restoraunt_group_name', models.CharField(blank=True, max_length=255, null=True)),
                ('order_number', models.BigIntegerField(db_index=True)),
                ('uniq_order_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('item_sale_event_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('dish_code', models.CharField(blank=True, max_length=100, null=True)),
                ('dish_name', models.CharField(blank=True, max_length=255, null=True)),
                ('dish_category_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('dish_category_name', models.CharField(blank=True, max_length=255, null=True)),
                ('dish_group_id', models.CharField(blank=True, max_length=100, null=True)),
                ('dish_group_name', models.CharField(blank=True, max_length=255, null=True)),
                ('dish_amount', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('dish_sum_before_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('dish_sum_after_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('discount_sum', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('bonus_sum', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('coupon_series', models.CharField(blank=True, max_length=100, null=True)),
                ('coupon_number', models.CharField(blank=True, max_length=100, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict, help_text='Оригинальная строка OLAP-ответа для аудита и повторной обработки.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='olap_sales_raw_lines', to='guests.guest')),
                ('sync_journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_lines', to='guests.olapchecksyncjournal')),
            ],
            options={
                'verbose_name': 'Сырая строка OLAP',
                'verbose_name_plural': 'Сырые строки OLAP',
                'db_table': 'olap_sales_raw_line',
            },
        ),
        migrations.AddIndex(
            model_name='olapchecksyncjournal',
            index=models.Index(fields=['status', 'next_try_at'], name='ocsj_status_next_idx'),
        ),
        migrations.AddIndex(
            model_name='olapchecksyncjournal',
            index=models.Index(fields=['order_number', 'business_date'], name='ocsj_ord_date_idx'),
        ),
        migrations.AddIndex(
            model_name='olapchecksyncjournal',
            index=models.Index(fields=['terminal_group_id', 'business_date'], name='ocsj_term_date_idx'),
        ),
        migrations.AddIndex(
            model_name='olapchecksyncjournal',
            index=models.Index(fields=['guest', 'business_date'], name='ocsj_guest_date_idx'),
        ),
        migrations.AddIndex(
            model_name='olapsalesrawline',
            index=models.Index(fields=['guest', 'business_date'], name='osrl_guest_date_idx'),
        ),
        migrations.AddIndex(
            model_name='olapsalesrawline',
            index=models.Index(fields=['department_id', 'business_date'], name='osrl_dept_date_idx'),
        ),
        migrations.AddIndex(
            model_name='olapsalesrawline',
            index=models.Index(fields=['order_number', 'business_date'], name='osrl_ord_date_idx'),
        ),
        migrations.AddIndex(
            model_name='olapsalesrawline',
            index=models.Index(fields=['dish_category_id', 'business_date'], name='osrl_cat_date_idx'),
        ),
    ]
