# Generated by Django 5.2.7 on 2026-03-19 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0019_olapchecksyncjournal_olapsalesrawline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OlapDishCategoryDict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_category_id', models.CharField(db_index=True, help_text='Уникальный идентификатор категории блюда в OLAP.', max_length=100, unique=True)),
                ('dish_category_name', models.CharField(help_text='Название категории блюда из OLAP.', max_length=255)),
                ('first_seen_at', models.DateTimeField(blank=True, db_index=True, help_text='Когда категория впервые встретилась в загруженных данных.', null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, db_index=True, help_text='Когда категория в последний раз встречалась в загруженных данных.', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Признак активности категории в справочнике.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Справочник категорий OLAP',
                'verbose_name_plural': 'Справочник категорий OLAP',
                'db_table': 'olap_dish_category_dict',
                'indexes': [models.Index(fields=['dish_category_name'], name='odcd_name_idx'), models.Index(fields=['is_active', 'dish_category_name'], name='odcd_active_name_idx')],
            },
        ),
    ]
