# Generated by Django 5.2.7 on 2026-03-19 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0020_olapdishcategorydict'),
    ]

    operations = [
        migrations.CreateModel(
            name='FocusCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Уникальный технический код фокусной категории.', max_length=80, unique=True)),
                ('name', models.CharField(help_text='Название фокусной категории.', max_length=150)),
                ('source_type', models.CharField(choices=[('olap_direct', 'Прямая категория OLAP'), ('virtual', 'Виртуальная категория')], db_index=True, help_text='Источник категории: прямая OLAP-категория или виртуальная категория.', max_length=20)),
                ('is_enabled', models.BooleanField(db_index=True, default=True, help_text='Включена ли категория в расчёты и отборы.')),
                ('priority_weight', models.PositiveIntegerField(default=1, help_text='Вес категории в рейтинговых формулах.')),
                ('tag_code', models.CharField(blank=True, db_index=True, help_text='Технический тег для группировок (например: meat, wine).', max_length=64, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Фокусная категория',
                'verbose_name_plural': 'Фокусные категории',
                'db_table': 'focus_category',
            },
        ),
        migrations.CreateModel(
            name='FocusCategoryNomenclatureResolved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_reason', models.CharField(choices=[('direct_olap', 'Прямая категория OLAP'), ('virtual_nomenclature', 'Виртуальная категория по номенклатурам'), ('virtual_olap_category', 'Виртуальная категория по OLAP-категориям')], db_index=True, help_text='Причина, по которой номенклатура вошла в фокусную категорию.', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('focus_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolved_nomenclatures', to='guests.focuscategory')),
            ],
            options={
                'verbose_name': 'Предрассчитанная связь фокусной категории и номенклатуры',
                'verbose_name_plural': 'Предрассчитанные связи фокусных категорий и номенклатур',
                'db_table': 'focus_category_nomenclature_resolved',
            },
        ),
        migrations.CreateModel(
            name='OlapNomenclatureDict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iiko_nomenclature_external_id', models.CharField(db_index=True, help_text='Внешний идентификатор номенклатуры (блюда) из iiko OLAP.', max_length=100, unique=True)),
                ('nomenclature_name', models.CharField(help_text='Название номенклатуры (блюда) из OLAP.', max_length=255)),
                ('iiko_dish_group_external_id', models.CharField(blank=True, db_index=True, help_text='Внешний идентификатор группы блюда из OLAP (если доступен).', max_length=100, null=True)),
                ('dish_group_name', models.CharField(blank=True, help_text='Название группы блюда из OLAP.', max_length=255, null=True)),
                ('first_seen_at', models.DateTimeField(blank=True, db_index=True, help_text='Когда номенклатура впервые встретилась в данных OLAP.', null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, db_index=True, help_text='Когда номенклатура в последний раз встретилась в данных OLAP.', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Участвует ли номенклатура в текущем справочнике.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Справочник номенклатуры OLAP',
                'verbose_name_plural': 'Справочник номенклатуры OLAP',
                'db_table': 'olap_nomenclature_dict',
            },
        ),
        migrations.CreateModel(
            name='VirtualCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Уникальный технический код виртуальной категории.', max_length=80, unique=True)),
                ('name', models.CharField(help_text='Название виртуальной категории.', max_length=150)),
                ('description', models.TextField(blank=True, help_text='Описание логики категории.', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Виртуальная категория',
                'verbose_name_plural': 'Виртуальные категории',
                'db_table': 'virtual_category',
            },
        ),
        migrations.CreateModel(
            name='VirtualCategoryNomenclatureLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Связь виртуальной категории с номенклатурой',
                'verbose_name_plural': 'Связи виртуальной категории с номенклатурой',
                'db_table': 'virtual_category_nomenclature_link',
            },
        ),
        migrations.CreateModel(
            name='VirtualCategoryOlapCategoryLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Связь виртуальной категории с OLAP-категорией',
                'verbose_name_plural': 'Связи виртуальной категории с OLAP-категориями',
                'db_table': 'virtual_category_olap_category_link',
            },
        ),
        migrations.RemoveIndex(
            model_name='olapdishcategorydict',
            name='odcd_name_idx',
        ),
        migrations.RemoveIndex(
            model_name='olapdishcategorydict',
            name='odcd_active_name_idx',
        ),
        migrations.RenameModel(
            old_name='OlapDishCategoryDict',
            new_name='OlapCategoryDict',
        ),
        migrations.AlterModelTable(
            name='olapcategorydict',
            table='olap_category_dict',
        ),
        migrations.RenameField(
            model_name='olapcategorydict',
            old_name='dish_category_id',
            new_name='iiko_category_external_id',
        ),
        migrations.RenameField(
            model_name='olapcategorydict',
            old_name='dish_category_name',
            new_name='category_name',
        ),
        migrations.AlterField(
            model_name='olapcategorydict',
            name='iiko_category_external_id',
            field=models.CharField(db_index=True, help_text='Внешний идентификатор категории из iiko OLAP.', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='olapcategorydict',
            name='category_name',
            field=models.CharField(help_text='Название категории из OLAP.', max_length=255),
        ),
        migrations.AlterField(
            model_name='olapcategorydict',
            name='first_seen_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Когда категория впервые встретилась в данных OLAP.', null=True),
        ),
        migrations.AlterField(
            model_name='olapcategorydict',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Когда категория в последний раз встретилась в данных OLAP.', null=True),
        ),
        migrations.AlterField(
            model_name='olapcategorydict',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Участвует ли категория в текущем справочнике.'),
        ),
        migrations.AddIndex(
            model_name='olapcategorydict',
            index=models.Index(fields=['category_name'], name='ocd_name_idx'),
        ),
        migrations.AddIndex(
            model_name='olapcategorydict',
            index=models.Index(fields=['is_active', 'category_name'], name='ocd_active_name_idx'),
        ),
        migrations.AddField(
            model_name='focuscategory',
            name='olap_category',
            field=models.ForeignKey(blank=True, help_text='Ссылка на категорию OLAP (только для source_type=olap_direct).', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='focus_category_rows', to='guests.olapcategorydict'),
        ),
        migrations.AddField(
            model_name='olapnomenclaturedict',
            name='olap_category',
            field=models.ForeignKey(help_text='Категория OLAP, к которой относится номенклатура.', on_delete=django.db.models.deletion.RESTRICT, related_name='nomenclatures', to='guests.olapcategorydict'),
        ),
        migrations.AddField(
            model_name='focuscategorynomenclatureresolved',
            name='nomenclature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='resolved_focus_categories', to='guests.olapnomenclaturedict'),
        ),
        migrations.AddIndex(
            model_name='virtualcategory',
            index=models.Index(fields=['is_active', 'name'], name='vc_active_name_idx'),
        ),
        migrations.AddField(
            model_name='focuscategory',
            name='virtual_category',
            field=models.ForeignKey(blank=True, help_text='Ссылка на виртуальную категорию (только для source_type=virtual).', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='focus_category_rows', to='guests.virtualcategory'),
        ),
        migrations.AddField(
            model_name='virtualcategorynomenclaturelink',
            name='nomenclature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='virtual_category_links', to='guests.olapnomenclaturedict'),
        ),
        migrations.AddField(
            model_name='virtualcategorynomenclaturelink',
            name='virtual_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nomenclature_links', to='guests.virtualcategory'),
        ),
        migrations.AddField(
            model_name='virtualcategoryolapcategorylink',
            name='olap_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='virtual_category_links', to='guests.olapcategorydict'),
        ),
        migrations.AddField(
            model_name='virtualcategoryolapcategorylink',
            name='virtual_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='olap_category_links', to='guests.virtualcategory'),
        ),
        migrations.AddIndex(
            model_name='olapnomenclaturedict',
            index=models.Index(fields=['olap_category', 'is_active'], name='ond_cat_active_idx'),
        ),
        migrations.AddIndex(
            model_name='olapnomenclaturedict',
            index=models.Index(fields=['nomenclature_name'], name='ond_name_idx'),
        ),
        migrations.AddIndex(
            model_name='focuscategorynomenclatureresolved',
            index=models.Index(fields=['nomenclature'], name='fcnr_nomenclature_idx'),
        ),
        migrations.AddIndex(
            model_name='focuscategorynomenclatureresolved',
            index=models.Index(fields=['focus_category', 'source_reason'], name='fcnr_focus_reason_idx'),
        ),
        migrations.AddConstraint(
            model_name='focuscategorynomenclatureresolved',
            constraint=models.UniqueConstraint(fields=('focus_category', 'nomenclature'), name='fcnr_focus_nomenclature_uniq'),
        ),
        migrations.AddIndex(
            model_name='focuscategory',
            index=models.Index(fields=['is_enabled', 'source_type', 'tag_code'], name='fc_enabled_src_tag_idx'),
        ),
        migrations.AddConstraint(
            model_name='focuscategory',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('source_type', 'olap_direct'), ('olap_category__isnull', False), ('virtual_category__isnull', True)), models.Q(('source_type', 'virtual'), ('virtual_category__isnull', False), ('olap_category__isnull', True)), _connector='OR'), name='focus_category_source_fk_chk'),
        ),
        migrations.AddIndex(
            model_name='virtualcategorynomenclaturelink',
            index=models.Index(fields=['nomenclature'], name='vcnl_nomenclature_idx'),
        ),
        migrations.AddConstraint(
            model_name='virtualcategorynomenclaturelink',
            constraint=models.UniqueConstraint(fields=('virtual_category', 'nomenclature'), name='vcnl_virtual_nomenclature_uniq'),
        ),
        migrations.AddIndex(
            model_name='virtualcategoryolapcategorylink',
            index=models.Index(fields=['olap_category'], name='vcocl_olap_category_idx'),
        ),
        migrations.AddConstraint(
            model_name='virtualcategoryolapcategorylink',
            constraint=models.UniqueConstraint(fields=('virtual_category', 'olap_category'), name='vcocl_virtual_olap_cat_uniq'),
        ),
    ]
