# Generated by Django 5.2.7 on 2026-03-19 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0021_focuscategory_focuscategorynomenclatureresolved_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_date', models.DateField(db_index=True)),
                ('department_id', models.CharField(blank=True, db_index=True, default='', help_text='Идентификатор заведения (Department.Id) из OLAP.', max_length=64)),
                ('department_name', models.CharField(blank=True, max_length=255, null=True)),
                ('order_number', models.BigIntegerField(db_index=True)),
                ('uniq_order_id', models.CharField(blank=True, db_index=True, default='', help_text='Уникальный идентификатор заказа из OLAP (если передан).', max_length=100)),
                ('gross_sum', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('net_sum', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('discount_sum', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('bonus_sum', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('items_count', models.PositiveIntegerField(default=0)),
                ('categories_count', models.PositiveIntegerField(default=0)),
                ('coupon_used', models.BooleanField(db_index=True, default=False)),
                ('coupon_series', models.CharField(blank=True, max_length=100, null=True)),
                ('coupon_number', models.CharField(blank=True, max_length=100, null=True)),
                ('order_type', models.CharField(blank=True, max_length=64, null=True)),
                ('is_delivery', models.BooleanField(db_index=True, default=False)),
                ('first_seen_at', models.DateTimeField(blank=True, db_index=True, help_text='Когда заказ впервые был замечен в сыром OLAP-слое.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_facts', to='guests.guest')),
            ],
            options={
                'verbose_name': 'Факт чека',
                'verbose_name_plural': 'Факты чеков',
                'db_table': 'order_fact',
                'indexes': [models.Index(fields=['guest', 'business_date'], name='of_guest_date_idx'), models.Index(fields=['department_id', 'business_date'], name='of_dept_date_idx'), models.Index(fields=['business_date', 'order_number'], name='of_date_order_idx')],
                'constraints': [models.UniqueConstraint(fields=('business_date', 'department_id', 'order_number', 'uniq_order_id'), name='order_fact_order_uniq')],
            },
        ),
    ]
