# Generated by Django 5.2.7 on 2026-03-19 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0022_orderfact'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestRestaurantDailyCategoryFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_date', models.DateField(db_index=True)),
                ('department_id', models.CharField(blank=True, db_index=True, default='', help_text='Идентификатор заведения (Department.Id) из OLAP.', max_length=64)),
                ('orders_count', models.PositiveIntegerField(default=0)),
                ('items_count', models.PositiveIntegerField(default=0)),
                ('sum_gross', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('sum_net', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('bonus_sum', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('focus_category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='daily_guest_facts', to='guests.focuscategory')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_category_facts', to='guests.guest')),
            ],
            options={
                'verbose_name': 'Дневной факт гостя по категории',
                'verbose_name_plural': 'Дневные факты гостей по категориям',
                'db_table': 'guest_restaurant_daily_category_fact',
                'indexes': [models.Index(fields=['guest', 'department_id', 'business_date'], name='grdcf_guest_dept_date_idx'), models.Index(fields=['focus_category', 'business_date'], name='grdcf_focus_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('business_date', 'guest', 'department_id', 'focus_category'), name='grdcf_unique_day_guest_dept_focus')],
            },
        ),
    ]
