# Generated by Django 5.2.7 on 2026-03-19 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0023_guestrestaurantdailycategoryfact'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestRestaurantWindowMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_of_date', models.DateField(db_index=True)),
                ('department_id', models.CharField(blank=True, db_index=True, default='', help_text='Идентификатор заведения (Department.Id) из OLAP.', max_length=64)),
                ('window_days', models.PositiveIntegerField(db_index=True, help_text='Размер окна в днях (например 7/14/30/60/180).')),
                ('orders_count', models.PositiveIntegerField(default=0)),
                ('visits_count', models.PositiveIntegerField(default=0)),
                ('avg_check_net', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('sum_net', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('bonus_in_sum', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('bonus_out_sum', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('last_visit_at', models.DateField(blank=True, db_index=True, null=True)),
                ('rating_score', models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='window_metrics', to='guests.guest')),
            ],
            options={
                'verbose_name': 'Оконная метрика гостя',
                'verbose_name_plural': 'Оконные метрики гостей',
                'db_table': 'guest_restaurant_window_metrics',
                'indexes': [models.Index(fields=['department_id', 'window_days', 'rating_score'], name='grwm_dept_win_rating_idx'), models.Index(fields=['guest', 'window_days', 'as_of_date'], name='grwm_guest_window_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('as_of_date', 'guest', 'department_id', 'window_days'), name='grwm_unique_asof_guest_dept_window')],
            },
        ),
    ]
