# Generated by Django 5.2.7 on 2026-03-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guests", "0024_guestrestaurantwindowmetrics"),
    ]

    operations = [
        migrations.CreateModel(
            name="TerminalDepartmentMap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "organization_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Идентификатор организации iiko (organizationId).",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "terminal_group_id",
                    models.CharField(
                        db_index=True,
                        help_text="Идентификатор терминальной группы iiko (terminalGroupId).",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "restoraunt_group_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Идентификатор группы ресторана из OLAP (RestorauntGroup.Id).",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "department_id",
                    models.CharField(
                        db_index=True,
                        help_text="Идентификатор заведения из OLAP (Department.Id).",
                        max_length=64,
                    ),
                ),
                (
                    "department_code",
                    models.CharField(
                        blank=True,
                        help_text="Код заведения из OLAP (Department.Code).",
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "department_name",
                    models.CharField(
                        blank=True,
                        help_text="Название заведения из OLAP (Department).",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "restaurant_section_id",
                    models.CharField(
                        blank=True,
                        help_text="Идентификатор секции зала из OLAP (RestaurantSection.Id).",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Активность сопоставления для рабочего контура.",
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Когда сопоставление было проверено вручную/операционно.",
                        null=True,
                    ),
                ),
                (
                    "source_order_num",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Контрольный номер чека, по которому подтверждали сопоставление.",
                        null=True,
                    ),
                ),
                (
                    "source_business_date",
                    models.DateField(
                        blank=True,
                        help_text="Контрольная бизнес-дата проверки сопоставления.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Сопоставление terminalGroupId -> Department.Id",
                "verbose_name_plural": "Сопоставления terminalGroupId -> Department.Id",
                "db_table": "terminal_department_map",
                "indexes": [
                    models.Index(
                        fields=["organization_id", "is_active"],
                        name="tdm_org_active_idx",
                    ),
                    models.Index(
                        fields=["department_id", "is_active"],
                        name="tdm_dept_active_idx",
                    ),
                ],
            },
        ),
    ]

