# Generated by Django 5.2.7 on 2026-03-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guests", "0025_terminaldepartmentmap"),
    ]

    operations = [
        migrations.CreateModel(
            name="GuestWorkbenchFilterPreset",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text="Уникальное имя пресета фильтра.",
                        max_length=120,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Короткое описание назначения пресета.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "window_days",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=30,
                        help_text="Размер окна метрик в днях.",
                    ),
                ),
                (
                    "department_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Department.Id для отбора. Пусто — все заведения.",
                        max_length=64,
                    ),
                ),
                (
                    "segment_code",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Код сегмента активности из workbench.",
                        max_length=32,
                    ),
                ),
                (
                    "focus_category_code",
                    models.SlugField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Код фокусной категории из workbench.",
                        max_length=80,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Включён ли пресет для отображения в интерфейсе.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Пресет фильтра workbench",
                "verbose_name_plural": "Пресеты фильтров workbench",
                "db_table": "guest_workbench_filter_preset",
            },
        ),
        migrations.AddIndex(
            model_name="guestworkbenchfilterpreset",
            index=models.Index(fields=["is_active", "updated_at"], name="gwfp_active_updated_idx"),
        ),
    ]
