# Generated by Django 5.2.7 on 2026-04-22 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guests", "0027_guestrestaurantwindowcategorymetrics"),
    ]

    operations = [
        migrations.CreateModel(
            name="GuestRestaurantDailyOrderFact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("business_date", models.DateField(db_index=True)),
                (
                    "department_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Идентификатор заведения (Department.Id) из OLAP.",
                        max_length=64,
                    ),
                ),
                ("orders_count", models.PositiveIntegerField(default=0)),
                ("sum_net", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("bonus_in_sum", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("bonus_out_sum", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "guest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_order_facts",
                        to="guests.guest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Дневной факт гостя по полным чекам",
                "verbose_name_plural": "Дневные факты гостей по полным чекам",
                "db_table": "guest_restaurant_daily_order_fact",
                "indexes": [
                    models.Index(fields=["guest", "department_id", "business_date"], name="grdof_g_dep_date_idx"),
                    models.Index(fields=["department_id", "business_date"], name="grdof_dep_date_idx"),
                    models.Index(fields=["business_date", "department_id"], name="grdof_date_dep_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("business_date", "guest", "department_id"),
                        name="grdof_uniq_day_guest_dept",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="GuestOrderFocusFact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("business_date", models.DateField(db_index=True)),
                (
                    "department_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Идентификатор заведения (Department.Id) из OLAP.",
                        max_length=64,
                    ),
                ),
                ("order_number", models.BigIntegerField(db_index=True)),
                (
                    "uniq_order_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Уникальный идентификатор заказа из OLAP (если передан).",
                        max_length=100,
                    ),
                ),
                ("items_count", models.PositiveIntegerField(default=0)),
                ("sum_focus_net", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "focus_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="order_focus_facts",
                        to="guests.focuscategory",
                    ),
                ),
                (
                    "guest",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_focus_facts",
                        to="guests.guest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Факт заказа по фокусной категории",
                "verbose_name_plural": "Факты заказов по фокусным категориям",
                "db_table": "guest_order_focus_fact",
                "indexes": [
                    models.Index(fields=["focus_category", "business_date", "department_id"], name="goff_f_cat_date_dep"),
                    models.Index(fields=["business_date", "department_id", "focus_category"], name="goff_date_dep_f_cat"),
                    models.Index(fields=["guest", "business_date", "focus_category"], name="goff_guest_date_focus"),
                    models.Index(
                        fields=["business_date", "department_id", "order_number", "uniq_order_id"],
                        name="goff_order_join_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("business_date", "department_id", "order_number", "uniq_order_id", "focus_category"),
                        name="goff_uniq_order_focus",
                    )
                ],
            },
        ),
    ]
