# Generated by Django 5.2.7 on 2026-04-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guests", "0028_guestrestaurantdailyorderfact_guestorderfocusfact"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="olapsalesrawline",
            index=models.Index(
                fields=["business_date", "department_id", "dish_code"],
                name="osrl_date_dep_dish_idx",
            ),
        ),
    ]
