# Generated by Django 5.2.7 on 2026-04-24 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guests", "0029_olapsalesrawline_date_dep_dish_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailing",
            name="is_archived",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Архивная кампания скрывается из списка по умолчанию и недоступна к запуску.",
            ),
        ),
    ]
