# Generated by Django 5.2.7 on 2026-05-05 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0030_mailing_is_archived'),
    ]

    operations = [
        migrations.CreateModel(
            name='VtelemaxSyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='vtelemax_recipients', help_text='Ключ синхронизации (singleton для данного потока).', max_length=64, unique=True)),
                ('watermark', models.DateTimeField(blank=True, db_index=True, help_text='Текущая нижняя граница `since` для delta.', null=True)),
                ('last_status', models.CharField(choices=[('idle', 'Ожидание'), ('running', 'В процессе'), ('success', 'Успешно'), ('error', 'Ошибка')], db_index=True, default='idle', max_length=16)),
                ('last_mode', models.CharField(blank=True, max_length=16, null=True)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('last_rows', models.PositiveIntegerField(default=0)),
                ('last_pages', models.PositiveIntegerField(default=0)),
                ('last_started_at', models.DateTimeField(blank=True, null=True)),
                ('last_finished_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vtelemax_sync_state',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VtelemaxRecipientChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.UUIDField()),
                ('platform', models.CharField(choices=[('telegram', 'Telegram'), ('max', 'MAX'), ('vk', 'VK')], db_index=True, max_length=32)),
                ('phone_e164', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ('external_id', models.CharField(blank=True, help_text='Идентификатор пользователя/чата в платформе, полученный из vtelemax.', max_length=128, null=True)),
                ('rules_accepted', models.BooleanField(default=False)),
                ('notifications_allowed', models.BooleanField(db_index=True, default=False)),
                ('is_registered', models.BooleanField(default=False)),
                ('state_updated_at', models.DateTimeField(blank=True, null=True)),
                ('account_created_at', models.DateTimeField(blank=True, null=True)),
                ('effective_updated_at', models.DateTimeField(blank=True, db_index=True, help_text='Временная метка изменения записи для delta-цикла.', null=True)),
                ('source_payload', models.JSONField(blank=True, default=dict, help_text='Последний сырой payload строки канала из API vtelemax.')),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_synced_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vtelemax_channels', to='guests.guest')),
                ('guest_binding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vtelemax_channels', to='guests.guestbotbinding')),
            ],
            options={
                'db_table': 'vtelemax_recipient_channels',
                'managed': True,
                'indexes': [models.Index(fields=['platform', 'notifications_allowed'], name='vtmx_ch_platform_optin_idx'), models.Index(fields=['guest', 'platform'], name='vtmx_ch_guest_platform_idx')],
                'constraints': [models.UniqueConstraint(fields=('person_id', 'platform'), name='vtelemax_channels_person_platform_uniq')],
            },
        ),
    ]
