# Generated by Django 5.2.7 on 2026-05-26 10:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0037_coupon_automation_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponAutoscenarioAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('phone_e164', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ('coupon_series', models.CharField(db_index=True, max_length=120)),
                ('coupon_code', models.CharField(max_length=120)),
                ('venue_code', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('venue_name', models.CharField(blank=True, max_length=255, null=True)),
                ('promo_text', models.TextField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('lifetime_expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('reserved', 'Зарезервирован'), ('sent', 'Отправлен'), ('used', 'Использован'), ('used_after_campaign', 'Использован после завершения акции'), ('expired', 'Истёк'), ('canceled', 'Отменён'), ('error', 'Ошибка')], db_index=True, default='reserved', max_length=32)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('used_order_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('vtelemax_sync_status', models.CharField(choices=[('pending', 'Ожидает синхронизации'), ('ok', 'Синхронизирован'), ('error', 'Ошибка синхронизации')], db_index=True, default='pending', max_length=16)),
                ('vtelemax_synced_at', models.DateTimeField(blank=True, null=True)),
                ('vtelemax_sync_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='guests.couponautomationconfig')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='autoscenario_assignments', to='guests.couponregistryentry')),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_autoscenario_assignments', to='guests.guest')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coupon_autoscenario_assignments', to='guests.notificationscenario')),
            ],
            options={
                'verbose_name': 'Назначение купона автосценария',
                'verbose_name_plural': 'Назначения купонов автосценариев',
                'db_table': 'coupon_autoscenario_assignments',
            },
        ),
        migrations.AddField(
            model_name='couponvtelemaxsyncqueue',
            name='autoscenario_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vtelemax_queue_events', to='guests.couponautoscenarioassignment'),
        ),
        migrations.CreateModel(
            name='CouponAutoscenarioRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('planned', 'Сформирован план'), ('reserved', 'Купоны зарезервированы'), ('sync_pending', 'Ожидает подтверждения vtelemax'), ('completed', 'Завершён'), ('error', 'Ошибка')], db_index=True, default='planned', max_length=24)),
                ('execution_mode', models.CharField(db_index=True, max_length=24)),
                ('scan_limit', models.PositiveIntegerField(default=0)),
                ('max_recipients_per_run', models.PositiveIntegerField(default=0)),
                ('scanned_guests', models.PositiveIntegerField(default=0)),
                ('matched_guests', models.PositiveIntegerField(default=0)),
                ('sendable_guests', models.PositiveIntegerField(default=0)),
                ('blocked_without_channel', models.PositiveIntegerField(default=0)),
                ('blocked_existing_active_coupon', models.PositiveIntegerField(default=0)),
                ('blocked_by_cooldown', models.PositiveIntegerField(default=0)),
                ('eligible_guests', models.PositiveIntegerField(default=0)),
                ('planned_assignments', models.PositiveIntegerField(default=0)),
                ('created_assignments', models.PositiveIntegerField(default=0)),
                ('queue_events_created', models.PositiveIntegerField(default=0)),
                ('coupon_shortage', models.PositiveIntegerField(default=0)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('blockers', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='guests.couponautomationconfig')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coupon_autoscenario_runs', to='guests.notificationscenario')),
            ],
            options={
                'verbose_name': 'Технический запуск купонного автосценария',
                'verbose_name_plural': 'Технические запуски купонных автосценариев',
                'db_table': 'coupon_autoscenario_runs',
            },
        ),
        migrations.AddField(
            model_name='couponautoscenarioassignment',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='guests.couponautoscenariorun'),
        ),
        migrations.AddIndex(
            model_name='couponautoscenariorun',
            index=models.Index(fields=['scenario', 'created_at'], name='cautorun_scen_created_idx'),
        ),
        migrations.AddIndex(
            model_name='couponautoscenariorun',
            index=models.Index(fields=['status', 'created_at'], name='cautorun_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='couponautoscenarioassignment',
            index=models.Index(fields=['scenario', 'status'], name='cautoass_scen_status_idx'),
        ),
        migrations.AddIndex(
            model_name='couponautoscenarioassignment',
            index=models.Index(fields=['status', 'vtelemax_sync_status'], name='cautoass_sync_status_idx'),
        ),
        migrations.AddIndex(
            model_name='couponautoscenarioassignment',
            index=models.Index(fields=['coupon_series', 'status'], name='cautoass_series_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='couponautoscenarioassignment',
            constraint=models.UniqueConstraint(fields=('run', 'guest'), name='cautoass_run_guest_uniq'),
        ),
        migrations.AddConstraint(
            model_name='couponautoscenarioassignment',
            constraint=models.UniqueConstraint(fields=('run', 'coupon_series', 'coupon_code'), name='cautoass_run_coupon_uniq'),
        ),
        migrations.AddConstraint(
            model_name='couponautoscenarioassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('person_id__isnull', False)), fields=('run', 'person_id'), name='cautoass_run_person_uniq'),
        ),
    ]
