# Generated by Codex on 2026-06-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guests", "0038_coupon_autoscenario_runs"),
    ]

    operations = [
        migrations.AddField(
            model_name="couponautoscenarioassignment",
            name="used_business_date",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
