# Generated by Django 5.2.7 on 2026-07-09 02:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0056_historical_telegram_channel'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestWelcomeRegistrationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('event_type', models.CharField(choices=[('guest_registered', 'Гость зарегистрирован')], db_index=True, default='guest_registered', max_length=64)),
                ('person_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('platform', models.CharField(choices=[('telegram', 'Telegram'), ('max', 'MAX'), ('vk', 'VK')], db_index=True, max_length=32)),
                ('phone_e164', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ('iiko_customer_id', models.CharField(blank=True, db_index=True, help_text='Идентификатор гостя iikoCard (`customerId`), переданный vtelemax.', max_length=64, null=True)),
                ('external_id', models.CharField(blank=True, max_length=128, null=True)),
                ('rules_accepted', models.BooleanField(default=False)),
                ('notifications_allowed', models.BooleanField(default=False)),
                ('is_registered', models.BooleanField(default=False)),
                ('registered_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('state_updated_at', models.DateTimeField(blank=True, null=True)),
                ('account_created_at', models.DateTimeField(blank=True, null=True)),
                ('effective_updated_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('new', 'Ожидает обработки'), ('channel_applied', 'Канал применён'), ('coupon_reserved', 'Купон зарезервирован'), ('skipped', 'Пропущено'), ('error', 'Ошибка')], db_index=True, default='new', max_length=24)),
                ('skip_reason', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ('error_text', models.TextField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('next_retry_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('profile', models.JSONField(blank=True, default=dict)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('payload_sha256', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('received_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coupon_assignment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='welcome_registration_event', to='guests.couponautoscenarioassignment')),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='welcome_registration_events', to='guests.guest')),
                ('vtelemax_channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='welcome_registration_events', to='guests.vtelemaxrecipientchannel')),
            ],
            options={
                'verbose_name': 'Событие welcome-регистрации гостя',
                'verbose_name_plural': 'События welcome-регистраций гостей',
                'db_table': 'guest_welcome_registration_events',
                'indexes': [models.Index(fields=['status', 'next_retry_at', 'received_at'], name='gwre_status_retry_idx'), models.Index(fields=['person_id', 'platform'], name='gwre_person_platform_idx'), models.Index(fields=['phone_e164', 'platform'], name='gwre_phone_platform_idx'), models.Index(fields=['guest', 'status'], name='gwre_guest_status_idx')],
            },
        ),
    ]
