# Generated by Django 5.2.7 on 2026-07-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guests", "0057_guest_welcome_registration_event"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="couponautomationconfig",
            name="cauto_scenario_type_chk",
        ),
        migrations.AlterField(
            model_name="couponautomationconfig",
            name="scenario_type",
            field=models.CharField(
                choices=[
                    ("inactive_days_coupon", "Гость не был N дней + купон"),
                    ("birthday_coupon", "День рождения + купон"),
                    ("birthdate_filled_coupon", "Дата рождения заполнена + купон"),
                    ("welcome_registration_coupon", "Регистрация гостя + приветственный купон"),
                ],
                db_index=True,
                default="inactive_days_coupon",
                help_text="Тип купонного автосценария: какая логика отбора гостей используется.",
                max_length=40,
            ),
        ),
        migrations.AddConstraint(
            model_name="couponautomationconfig",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    scenario_type__in=[
                        "inactive_days_coupon",
                        "birthday_coupon",
                        "birthdate_filled_coupon",
                        "welcome_registration_coupon",
                    ]
                ),
                name="cauto_scenario_type_chk",
            ),
        ),
    ]
