"""Идемпотентно создаёт схему интерактивных сообщений.

Миграция намеренно разделяет состояние Django и физические операции базы.
Это необходимо для окружений, где часть схемы могла быть подготовлена вручную
или предыдущим незавершённым запуском. Совместимые отсутствующие объекты
создаются, а несовместимая структура останавливает миграцию с понятной ошибкой.
"""

# Generated by Django 5.2.7 on 2026-08-20 09:38

import django.db.models.deletion
from django.db import migrations, models


INTERACTION_TABLE = "message_interactions"
EVENT_TABLE = "message_interaction_events"


class InteractionSchemaError(RuntimeError):
    """Ошибка несовместимой частично созданной схемы интерактивности."""


def _normalized(value):
    """Возвращает имя объекта в форме, используемой интроспекцией базы."""

    return str(value or "").casefold()


def _table_names(connection):
    """Возвращает множество существующих таблиц без учёта регистра."""

    with connection.cursor() as cursor:
        return {_normalized(name) for name in connection.introspection.table_names(cursor)}


def _column_descriptions(connection, table_name):
    """Возвращает описания столбцов таблицы по нормализованному имени."""

    with connection.cursor() as cursor:
        descriptions = connection.introspection.get_table_description(cursor, table_name)
    return {_normalized(description.name): description for description in descriptions}


def _constraints(connection, table_name):
    """Возвращает ограничения и индексы таблицы по нормализованному имени."""

    with connection.cursor() as cursor:
        discovered = connection.introspection.get_constraints(cursor, table_name)
    return {_normalized(name): details for name, details in discovered.items()}


def _table_has_rows(schema_editor, table_name):
    """Проверяет наличие хотя бы одной строки без полного просмотра таблицы."""

    quoted_table = schema_editor.quote_name(table_name)
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(f"SELECT 1 FROM {quoted_table} LIMIT 1")
        return cursor.fetchone() is not None


def _column_type_family(connection, description):
    """Возвращает обобщённый тип столбца по данным интроспекции."""

    try:
        return connection.introspection.get_field_type(description.type_code, description)
    except (KeyError, TypeError):
        return ""


def _allowed_type_families(field):
    """Определяет совместимые типы базы для поля Django."""

    internal_type = field.get_internal_type()
    if isinstance(field, (models.ForeignKey, models.OneToOneField)):
        internal_type = field.target_field.get_internal_type()

    families = {
        "BigAutoField": {"BigAutoField", "BigIntegerField", "AutoField", "IntegerField"},
        "BigIntegerField": {"BigAutoField", "BigIntegerField", "AutoField", "IntegerField"},
        "UUIDField": {"UUIDField", "CharField"},
        "CharField": {"CharField", "TextField"},
        "DateTimeField": {"DateTimeField"},
    }
    return families.get(internal_type, {internal_type})


def _validate_column(connection, model, field, description):
    """Проверяет тип, обязательность и размер существующего столбца."""

    actual_type = _column_type_family(connection, description)
    allowed_types = _allowed_type_families(field)
    if actual_type and actual_type not in allowed_types:
        raise InteractionSchemaError(
            f"Таблица {model._meta.db_table}: столбец {field.column} имеет "
            f"несовместимый тип {actual_type}; ожидался один из {sorted(allowed_types)}."
        )

    actual_null = bool(description.null_ok)
    if actual_null != bool(field.null):
        expected = "разрешает NULL" if field.null else "запрещает NULL"
        actual = "разрешает NULL" if actual_null else "запрещает NULL"
        raise InteractionSchemaError(
            f"Таблица {model._meta.db_table}: столбец {field.column} {actual}, "
            f"но модель {expected}."
        )

    actual_size = getattr(description, "internal_size", None)
    expected_size = getattr(field, "max_length", None)
    if actual_size and expected_size and actual_size < expected_size:
        raise InteractionSchemaError(
            f"Таблица {model._meta.db_table}: длина столбца {field.column} "
            f"равна {actual_size}, требуется не менее {expected_size}."
        )


def _constraint_columns(details):
    """Возвращает нормализованный кортеж столбцов ограничения."""

    return tuple(_normalized(column) for column in (details.get("columns") or ()))


def _condition_field_names(condition):
    """Извлекает имена полей из дерева условия `Q`."""

    names = set()
    for child in getattr(condition, "children", ()):
        if isinstance(child, tuple):
            names.add(str(child[0]).split("__", 1)[0])
        else:
            names.update(_condition_field_names(child))
    return names


def _expected_constraint_columns(model, constraint):
    """Возвращает ожидаемые столбцы именованного ограничения."""

    if isinstance(constraint, models.UniqueConstraint):
        return tuple(
            _normalized(model._meta.get_field(field_name).column)
            for field_name in constraint.fields
        )
    if isinstance(constraint, models.CheckConstraint):
        return tuple(
            sorted(
                _normalized(model._meta.get_field(field_name).column)
                for field_name in _condition_field_names(constraint.condition)
            )
        )
    return ()


def _has_primary_key(discovered, field):
    expected = (_normalized(field.column),)
    return any(
        details.get("primary_key") and _constraint_columns(details) == expected
        for details in discovered.values()
    )


def _has_unique_column(discovered, field):
    expected = (_normalized(field.column),)
    return any(
        details.get("unique") and _constraint_columns(details) == expected
        for details in discovered.values()
    )


def _has_foreign_key(discovered, field):
    expected_columns = (_normalized(field.column),)
    target = (
        _normalized(field.target_field.model._meta.db_table),
        _normalized(field.target_field.column),
    )
    return any(
        _constraint_columns(details) == expected_columns
        and tuple(_normalized(value) for value in (details.get("foreign_key") or ())) == target
        for details in discovered.values()
    )


def _add_foreign_key(schema_editor, model, field):
    """Добавляет отсутствующий внешний ключ через изменение описания поля."""

    old_field = field.clone()
    old_field.set_attributes_from_name(field.name)
    old_field.model = model
    old_field.db_constraint = False
    schema_editor.alter_field(model, old_field, field, strict=True)


def _ensure_named_constraint(schema_editor, model, constraint):
    discovered = _constraints(schema_editor.connection, model._meta.db_table)
    details = discovered.get(_normalized(constraint.name))
    if details is None:
        schema_editor.add_constraint(model, constraint)
        return

    actual_columns = _constraint_columns(details)
    expected_columns = _expected_constraint_columns(model, constraint)
    if isinstance(constraint, models.CheckConstraint):
        is_compatible = details.get("check") and set(actual_columns) == set(expected_columns)
    elif isinstance(constraint, models.UniqueConstraint):
        is_compatible = details.get("unique") and actual_columns == expected_columns
    else:
        is_compatible = True

    if not is_compatible:
        raise InteractionSchemaError(
            f"Таблица {model._meta.db_table}: объект {constraint.name} существует, "
            f"но имеет несовместимую форму и столбцы {actual_columns}."
        )


def _ensure_named_index(schema_editor, model, index):
    discovered = _constraints(schema_editor.connection, model._meta.db_table)
    details = discovered.get(_normalized(index.name))
    if details is None:
        schema_editor.add_index(model, index)
        return

    expected_columns = tuple(
        _normalized(model._meta.get_field(field_name).column)
        for field_name in index.fields
    )
    actual_columns = _constraint_columns(details)
    if (
        not details.get("index")
        or details.get("unique")
        or actual_columns != expected_columns
    ):
        raise InteractionSchemaError(
            f"Таблица {model._meta.db_table}: индекс {index.name} существует, "
            f"но имеет несовместимую форму и столбцы {actual_columns}."
        )


def _ensure_unique_field(schema_editor, model, field, constraint_name):
    discovered = _constraints(schema_editor.connection, model._meta.db_table)
    if _has_unique_column(discovered, field):
        return
    schema_editor.add_constraint(
        model,
        models.UniqueConstraint(fields=[field.name], name=constraint_name),
    )


def _ensure_source_field(schema_editor, model, field_name, constraint_name):
    """Добавляет поле выбора набора в существующую исходную сущность."""

    connection = schema_editor.connection
    table_name = model._meta.db_table
    if _normalized(table_name) not in _table_names(connection):
        raise InteractionSchemaError(
            f"Не найдена обязательная существующая таблица {table_name}. "
            "Сначала восстановите предыдущие миграции приложения guests."
        )

    field = model._meta.get_field(field_name)
    columns = _column_descriptions(connection, table_name)
    description = columns.get(_normalized(field.column))
    if description is None:
        schema_editor.add_field(model, field)
        columns = _column_descriptions(connection, table_name)
        description = columns.get(_normalized(field.column))

    if description is None:
        raise InteractionSchemaError(
            f"Не удалось создать столбец {table_name}.{field.column}."
        )
    _validate_column(connection, model, field, description)

    constraint = next(
        item for item in model._meta.constraints if item.name == constraint_name
    )
    _ensure_named_constraint(schema_editor, model, constraint)


def _recreate_empty_sqlite_table(schema_editor, model):
    """Без потери данных заменяет пустую несовместимо неполную таблицу SQLite."""

    table_name = model._meta.db_table
    if _table_has_rows(schema_editor, table_name):
        raise InteractionSchemaError(
            f"Таблица {table_name} содержит данные и не имеет всех обязательных столбцов. "
            "Автоматическое перестроение заблокировано."
        )
    schema_editor.execute(f"DROP TABLE {schema_editor.quote_name(table_name)}")
    schema_editor.create_model(model)


def _ensure_new_model_table(schema_editor, model):
    """Создаёт либо строго проверяет таблицу новой модели."""

    connection = schema_editor.connection
    table_name = model._meta.db_table
    if _normalized(table_name) not in _table_names(connection):
        schema_editor.create_model(model)
        return

    columns = _column_descriptions(connection, table_name)
    missing_fields = [
        field
        for field in model._meta.local_fields
        if _normalized(field.column) not in columns
    ]

    for field in model._meta.local_fields:
        description = columns.get(_normalized(field.column))
        if description is not None:
            _validate_column(connection, model, field, description)

    if missing_fields and connection.vendor == "sqlite" and not _table_has_rows(schema_editor, table_name):
        _recreate_empty_sqlite_table(schema_editor, model)
        return

    for field in missing_fields:
        if _table_has_rows(schema_editor, table_name) and (
            field.primary_key or field.unique or not field.null or field.is_relation
        ):
            raise InteractionSchemaError(
                f"Таблица {table_name} содержит данные, но в ней отсутствует "
                f"обязательный столбец {field.column}. Автоматическое добавление заблокировано."
            )
        schema_editor.add_field(model, field)

    columns = _column_descriptions(connection, table_name)
    for field in model._meta.local_fields:
        description = columns.get(_normalized(field.column))
        if description is None:
            raise InteractionSchemaError(
                f"Таблица {table_name}: отсутствует обязательный столбец {field.column}."
            )
        _validate_column(connection, model, field, description)

    discovered = _constraints(connection, table_name)
    primary_key = model._meta.pk
    if not _has_primary_key(discovered, primary_key):
        raise InteractionSchemaError(
            f"Таблица {table_name}: столбец {primary_key.column} не является первичным ключом."
        )

    for field in model._meta.local_fields:
        if field.unique and not field.primary_key:
            _ensure_unique_field(
                schema_editor,
                model,
                field,
                f"{table_name}_{field.column}_uniq",
            )

        if isinstance(field, (models.ForeignKey, models.OneToOneField)) and field.db_constraint:
            discovered = _constraints(connection, table_name)
            if not _has_foreign_key(discovered, field):
                _add_foreign_key(schema_editor, model, field)

    for constraint in model._meta.constraints:
        _ensure_named_constraint(schema_editor, model, constraint)
    for index in model._meta.indexes:
        _ensure_named_index(schema_editor, model, index)


def ensure_message_interaction_schema(apps, schema_editor):
    """Приводит физическую схему к утверждённому состоянию без дублей."""

    Mailing = apps.get_model("guests", "Mailing")
    NotificationScenario = apps.get_model("guests", "NotificationScenario")
    MessageInteraction = apps.get_model("guests", "MessageInteraction")
    MessageInteractionEvent = apps.get_model("guests", "MessageInteractionEvent")

    _ensure_source_field(schema_editor, Mailing, "button_set", "mailings_button_set_chk")
    _ensure_source_field(
        schema_editor,
        NotificationScenario,
        "button_set",
        "ns_button_set_chk",
    )
    _ensure_new_model_table(schema_editor, MessageInteraction)
    _ensure_new_model_table(schema_editor, MessageInteractionEvent)


def noop_reverse(apps, schema_editor):
    """Обратная миграция не удаляет накопленные события взаимодействия."""


STATE_OPERATIONS = [
    migrations.AddField(
        model_name="mailing",
        name="button_set",
        field=models.CharField(
            choices=[
                ("none", "Без кнопок"),
                ("rating_menu", "Оценка и главное меню"),
                ("rating_coupons", "Оценка и купоны"),
            ],
            default="none",
            help_text="Набор интерактивных кнопок для современных маршрутов рассылки.",
            max_length=20,
        ),
    ),
    migrations.AddConstraint(
        model_name="mailing",
        constraint=models.CheckConstraint(
            condition=models.Q(button_set__in=["none", "rating_menu", "rating_coupons"]),
            name="mailings_button_set_chk",
        ),
    ),
    migrations.AddField(
        model_name="notificationscenario",
        name="button_set",
        field=models.CharField(
            choices=[
                ("none", "Без кнопок"),
                ("rating_menu", "Оценка и главное меню"),
                ("rating_coupons", "Оценка и купоны"),
            ],
            default="none",
            help_text="Набор интерактивных кнопок для сообщений этого сценария.",
            max_length=20,
        ),
    ),
    migrations.AddConstraint(
        model_name="notificationscenario",
        constraint=models.CheckConstraint(
            condition=models.Q(button_set__in=["none", "rating_menu", "rating_coupons"]),
            name="ns_button_set_chk",
        ),
    ),
    migrations.CreateModel(
        name="MessageInteraction",
        fields=[
            ("id", models.BigAutoField(primary_key=True, serialize=False)),
            (
                "dispatch_task",
                models.OneToOneField(
                    help_text="Задача, представляющая конкретную отправку сообщения.",
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name="message_interaction",
                    to="guests.dispatchtask",
                ),
            ),
            (
                "button_set",
                models.CharField(
                    choices=[
                        ("rating_menu", "Оценка и главное меню"),
                        ("rating_coupons", "Оценка и купоны"),
                    ],
                    help_text="Фактически отправленный набор интерактивных кнопок.",
                    max_length=20,
                ),
            ),
            ("created_at", models.DateTimeField(auto_now_add=True)),
        ],
        options={
            "verbose_name": "Интерактивность сообщения",
            "verbose_name_plural": "Интерактивности сообщений",
            "db_table": INTERACTION_TABLE,
            "constraints": [
                models.CheckConstraint(
                    condition=models.Q(button_set__in=["rating_menu", "rating_coupons"]),
                    name="mi_button_set_chk",
                ),
            ],
        },
    ),
    migrations.CreateModel(
        name="MessageInteractionEvent",
        fields=[
            ("id", models.BigAutoField(primary_key=True, serialize=False)),
            (
                "event_id",
                models.UUIDField(
                    help_text="Уникальный идентификатор события, сформированный vtelemax.",
                    unique=True,
                ),
            ),
            (
                "interaction",
                models.ForeignKey(
                    db_index=False,
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name="events",
                    to="guests.messageinteraction",
                ),
            ),
            (
                "action",
                models.CharField(
                    choices=[
                        ("l", "Нравится"),
                        ("d", "Не нравится"),
                        ("c", "В купоны"),
                        ("m", "Меню"),
                    ],
                    max_length=1,
                ),
            ),
            (
                "occurred_at",
                models.DateTimeField(
                    help_text=(
                        "Время первой успешной долговечной фиксации обратного вызова "
                        "на сервере vtelemax."
                    )
                ),
            ),
            ("received_at", models.DateTimeField(auto_now_add=True)),
            (
                "result",
                models.CharField(
                    choices=[
                        ("accepted", "Принято"),
                        ("rating_already_recorded", "Оценка уже зафиксирована"),
                    ],
                    max_length=32,
                ),
            ),
            (
                "provider_message_id",
                models.CharField(
                    blank=True,
                    help_text="Вспомогательный идентификатор сообщения на стороне платформы.",
                    max_length=255,
                    null=True,
                ),
            ),
        ],
        options={
            "verbose_name": "Событие взаимодействия с сообщением",
            "verbose_name_plural": "События взаимодействия с сообщениями",
            "db_table": EVENT_TABLE,
            "constraints": [
                models.CheckConstraint(
                    condition=models.Q(action__in=["l", "d", "c", "m"]),
                    name="mie_action_chk",
                ),
                models.CheckConstraint(
                    condition=models.Q(result__in=["accepted", "rating_already_recorded"]),
                    name="mie_result_chk",
                ),
                models.CheckConstraint(
                    condition=(
                        models.Q(result="accepted")
                        | models.Q(
                            result="rating_already_recorded",
                            action__in=["l", "d"],
                        )
                    ),
                    name="mie_result_action_chk",
                ),
                models.UniqueConstraint(
                    fields=["interaction"],
                    condition=models.Q(action__in=["l", "d"], result="accepted"),
                    name="mie_one_accepted_rating_uniq",
                ),
            ],
            "indexes": [
                models.Index(fields=["interaction"], name="mie_interaction_idx"),
            ],
        },
    ),
]


class Migration(migrations.Migration):
    dependencies = [
        ("guests", "0059_seed_welcome_coupon_autoscenario"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=STATE_OPERATIONS,
        ),
        migrations.RunPython(ensure_message_interaction_schema, noop_reverse),
    ]
